<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yara</string>
		<string>yar</string>
	</array>
	<key>name</key>
	<string>YARA</string>
	<key>patterns</key>
	<array>
		<dict>
			<!-- block and line comments -->
			<key>include</key>
			<string>#comment</string>
			<!-- true/false -->
			<key>include</key>
			<string>#constant</string>
			<!-- general sections of the document -->
			<key>include</key>
			<string>#entity</key>
			<!-- miscellaneous -->
			<key>include</key>
			<string>#keyword</string>
			<!-- words that start with '$' -->
			<key>include</key>
			<string>#variable</string>
			<!-- YARA meta keywords -->
			<key>include</key>
			<string>#meta</string>
			<!-- strings, hex, regex -->
			<key>include</key>
			<string>#strings</string>
			<!-- invalid/deprecated -->
			<key>include</key>
			<string>#invalid</string>
			<!-- if/else, etc. -->
<!--
			Can be covered by keyword.control, keyword.operator, etc. instead
			<key>include</key>
			<string>#conditions</string>
-->
		</dict>
	</array>
	<key>smartTypingPairs</key>
	<array>
		<array>
			<string>'</string>
			<string>'</string>
		</array>
		<array>
			<string>"</string>
			<string>"</string>
		</array>
		<array>
			<string>(</string>
			<string>)</string>
		</array>
		<array>
			<string>{</string>
			<string>}</string>
		</array>
		<array>
			<string>[</string>
			<string>]</string>
		</array>
		<array>
			<string>/*</string>
			<string>*/</string>
		</array>
	</array>
</dict>
</plist>