<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yara</string>
		<string>yar</string>
	</array>
	<key>name</key>
	<string>YARA</string>
	<key>scopeName</key>
	<string>source.yara</string>
	<key>patterns</key>
	<array>
		<!-- Comment blocks : Single-line and blocks -->
		<!-- single line -->
		<dict>
			<key>name</key>
			<string>comment.line.double-slash.yara</string>
			<key>match</key>
			<string>//.*\n</string>
		</dict>
		<!-- block -->
		<dict>
			<key>name</key>
			<string>comment.block.yara</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<!-- Constants : BOOL, Ints, etc. -->
		<!-- BOOLEAN-->
		<dict>
			<key>name</key>
			<string>constant.language.boolean.true.yara</string>
			<key>match</key>
			<string>(\btrue\b|\bfalse\b)</string>
		</dict>
		<!-- 0xHEX -->
		<dict>
			<key>name</key>
			<string>constant.numeric.hex.yara</string>
			<key>match</key>
			<string>\b0(x|X)[0-9A-Fa-f]+\b</string>
		</dict>
		<!-- Decimals -->
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.yara</string>
			<key>match</key>
			<string>\b[0-9]+\b</string>
		</dict>
		<!-- Keywords : Specific to YARA -->
		<!-- and -->
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.and.yara</string>
			<key>match</key>
			<string>\band\b</string>
		</dict>
		<!-- or -->
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.or.yara</string>
			<key>match</key>
			<string>\bor\b</string>
		</dict>
		<!-- not -->
		<dict>
			<key>name</key>
			<string>keyword.operator.logical.not.yara</string>
			<key>match</key>
			<string>\bnot\b</string>
		</dict>
		<!-- condition: -->
		<dict>
			<key>name</key>
			<string>keyword.other.condition.yara</string>
			<key>match</key>
			<string>\bcondition:\n$</string>
		</dict>
		<!-- strings: -->
		<dict>
			<key>name</key>
			<string>keyword.other.strings.yara</string>
			<key>match</key>
			<string>\bstrings:\n$</string>
		</dict>
		<!-- meta: -->
		<dict>
			<key>name</key>
			<string>keyword.other.meta.yara</string>
			<key>match</key>
			<string>\bmeta:\n$</string>
		</dict>
		<!-- rule -->
		<dict>
			<key>name</key>
			<string>keyword.other.rule.yara</string>
			<key>match</key>
			<string>\brule\b</string>
		</dict>
		<!-- all -->
		<dict>
			<key>name</key>
			<string>keyword.other.all.yara</string>
			<key>match</key>
			<string>\ball\b</string>
		</dict>
		<!-- Variables : Any word that starts with '$' -->
		<dict>
			<key>name</key>
			<string>variable.parameter.source.yara</string>
			<key>match</key>
			<string>\$\S+\b</string>
		</dict>
		<!-- Strings : Normal strings and hex strings -->
		<!-- single quotes, remove possible contractions -->
		<dict>
			<key>name</key>
			<string>string.single.yara</string>
			<key>match</key>
			<string>(?i)(\'.*[^(n|t|e|i|o|u|y)]\'[^(t|s|d|l|v|m|r)])(?-i)</string>
		</dict>
		<!-- double quotes -->
		<dict>
			<key>name</key>
			<string>string.double.yara</string>
			<key>match</key>
			<string>\".*\"</string>
		</dict>
		<!-- regexp -->
		<dict>
			<key>name</key>
			<string>string.regexp.yara</string>
			<key>match</key>
			<string>/.*/</string>
		</dict>
		<!-- hex -->
		<dict>
			<key>name</key>
			<string>string.hex.yara</string>
			<!--
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>match</key>
			<string>[A-Fa-f0-9]</string>
			-->
			<key>match</key>
			<string>\{[0-9a-fA-F\s\?]+\}</string>
		</dict>
		<!-- hex wildcards -->
		<dict>
			<key>name</key>
			<string>string.regexp.wildcard.yara</string>
			<key>begin</key>
			<string>{</string>
			<key>match</key>
			<string>\?</string>
			<key>end</key>
			<string>}</string>
		</dict>
		<!-- Storage strings : mostly data types -->
		<dict>
			<key>name</key>
			<string>storage.type.any.yara</string>
			<key>match</key>
			<string>\bany\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.ascii.yara</string>
			<key>match</key>
			<string>\bascii\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.at.yara</string>
			<key>match</key>
			<string>\bat\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.condition.yara</string>
			<key>match</key>
			<string>\bcondition\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.contains.yara</string>
			<key>match</key>
			<string>\bcontains\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.entrypoint.yara</string>
			<key>match</key>
			<string>\bentrypoint\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.filesize.yara</string>
			<key>match</key>
			<string>\bfilesize\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.fullword.yara</string>
			<key>match</key>
			<string>\bfullword\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.for.yara</string>
			<key>match</key>
			<string>\bfor\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.global.yara</string>
			<key>match</key>
			<string>\bglobal\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.in.yara</string>
			<key>match</key>
			<string>\bin\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.import.yara</string>
			<key>match</key>
			<string>\bimport\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.include.yara</string>
			<key>match</key>
			<string>\binclude\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.int8.yara</string>
			<key>match</key>
			<string>\bint8\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.int16.yara</string>
			<key>match</key>
			<string>\bint16\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.int32.yara</string>
			<key>match</key>
			<string>\bint32\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.int8be.yara</string>
			<key>match</key>
			<string>\bint8be\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.int16be.yara</string>
			<key>match</key>
			<string>\bint16be\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.int32be.yara</string>
			<key>match</key>
			<string>\bint32be\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.matches.yara</string>
			<key>match</key>
			<string>\bmatches\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.meta.yara</string>
			<key>match</key>
			<string>\bmeta\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.nocase.yara</string>
			<key>match</key>
			<string>\bnocase\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.of.yara</string>
			<key>match</key>
			<string>\bof\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.private.yara</string>
			<key>match</key>
			<string>\bprivate\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.strings.yara</string>
			<key>match</key>
			<string>\bstrings\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.them.yara</string>
			<key>match</key>
			<string>\bthem\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.uint8.yara</string>
			<key>match</key>
			<string>\buint8\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.uint16.yara</string>
			<key>match</key>
			<string>\buint16\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.uint32.yara</string>
			<key>match</key>
			<string>\buint32\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.uint8be.yara</string>
			<key>match</key>
			<string>\buint8be\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.uint16be.yara</string>
			<key>match</key>
			<string>\buint16be\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.uint32be.yara</string>
			<key>match</key>
			<string>\buint32be\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.wide.yara</string>
			<key>match</key>
			<string>\bwide\b</string>
		</dict>
	</array>
	<!-- define pairs of characters so that the second character gets
	automatically inserted when you type the first character -->
	<key>smartTypingPairs</key>
	<array>
		<array>
			<string>'</string>
			<string>'</string>
		</array>
		<array>
			<string>"</string>
			<string>"</string>
		</array>
		<array>
			<string>(</string>
			<string>)</string>
		</array>
		<array>
			<string>{</string>
			<string>}</string>
		</array>
		<array>
			<string>[</string>
			<string>]</string>
		</array>
		<array>
			<string>/*</string>
			<string>*/</string>
		</array>
	</array>
	<key>highlightPairs</key>
	<array>
		<array>
			<string>'</string>
			<string>'</string>
		</array>
		<array>
			<string>"</string>
			<string>"</string>
		</array>
		<array>
			<string>(</string>
			<string>)</string>
		</array>
		<array>
			<string>{</string>
			<string>}</string>
		</array>
		<array>
			<string>[</string>
			<string>]</string>
		</array>
		<array>
			<string>/*</string>
			<string>*/</string>
		</array>
	</array>
</dict>
</plist>