<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yara</string>
		<string>yar</string>
	</array>
	<key>name</key>
	<string>YARA</string>
	<key>scopeName</key>
	<string>source.yara</string>
	<key>patterns</key>
	<array>
		<dict>
			<!-- block and line comments -->
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<!-- true/false -->
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<!-- general sections of the document -->
			<key>include</key>
			<string>#entity</key>
		</dict>
		<dict>
			<!-- miscellaneous -->
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<!-- words that start with '$' -->
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<!-- YARA meta keywords -->
			<key>include</key>
			<string>#meta</string>
		</dict>
		<dict>
			<!-- strings, hex, regex -->
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<!-- global -->
			<key>include</key>
			<string>#storage</string>
		</dict>
		<dict>
			<!-- invalid/deprecated -->
			<key>include</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.modifier.yara</string>
					<!-- match 'global' YARA statements - can be preceded with whitespace -->
					<key>match</key>
					<string>^\bglobal\b</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.yara</string>
					<!-- match everything on a line after '//' -->
					<key>match</key>
					<string>//.*\n</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.yara</string>
					<!-- match everything between (and including) /* */ -->
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.true.yara</string>
					<!-- match 'true', but not 'strue' or 'trues' -->
					<key>match</key>
					<string>\btrue\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.false.yara</string>
					<!-- match 'false', but not 'sfalse' or 'falses' -->
					<key>match</key>
					<string>\bfalse\b</string>
			</array>
		</dict>
		<key>entity</key>
		<dict>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.and.yara</string>
					<key>match</key>
					<string> and </string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.or.yara</string>
					<key>match</key>
					<string> or </string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.not.yara</string>
					<key>match</key>
					<string> not </string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.rule.yara</string>
					<key>match</key>
					<string>(\s)*rule </string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.condition.yara</string>
					<key>match</key>
					<string>^(\s)*condition:(\s)*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.strings.yara</string>
					<key>match</key>
					<string>^(\s)*strings:(\s)*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.meta.yara</string>
					<key>match</key>
					<string>^(\s)*meta:(\s)*</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.yara</string>
					<!-- match a string of non-space characters beginning with '$' -->
					<key>match</key>
					<string>\$\S+</string>
				</dict>
			</array>
		</dict>
		<key>meta</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.source.yara</string>
					<key>match</key>
					<string></string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.single.yara</string>
					<!-- match all characters between a pair of single quotes -->
					<key>match</key>
					<string>\'.*\'</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.double.yara</string>
					<!-- match all characters between a pair of double quotes -->
					<key>match</key>
					<string>\".*\"</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.regexp.yara</string>
					<!-- ??? -->
					<key>match</key>
					<string></string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.hex.yara</string>
					<!-- match pairs of hex values with surrounding spaces : NOT VERY GOOD -->
					<key>match</key>
					<string>\s[0-9A-Fa-f]{2}\s</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
		</dict>
	</dict>
	<!-- define pairs of characters so that the second character gets
	automatically inserted when you type the first character -->
	<key>smartTypingPairs</key>
	<array>
		<array>
			<string>'</string>
			<string>'</string>
		</array>
		<array>
			<string>"</string>
			<string>"</string>
		</array>
		<array>
			<string>(</string>
			<string>)</string>
		</array>
		<array>
			<string>{</string>
			<string>}</string>
		</array>
		<array>
			<string>[</string>
			<string>]</string>
		</array>
		<array>
			<string>/*</string>
			<string>*/</string>
		</array>
	</array>
	<key>highlightPairs</key>
	<array>
		<array>
			<string>'</string>
			<string>'</string>
		</array>
		<array>
			<string>"</string>
			<string>"</string>
		</array>
		<array>
			<string>(</string>
			<string>)</string>
		</array>
		<array>
			<string>{</string>
			<string>}</string>
		</array>
		<array>
			<string>[</string>
			<string>]</string>
		</array>
		<array>
			<string>/*</string>
			<string>*/</string>
		</array>
	</array>
</dict>
</plist>